version: 2

registries:
  chainguard-npm:
    type: npm-registry
    url: https://libraries.cgr.dev/javascript/
    username: ${{secrets.CHAINGUARD_PULL_TOKEN_USERNAME}}
    password: ${{secrets.CHAINGUARD_PULL_TOKEN_PASSWORD}}
    replaces-base: true

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - chainguard-npm
    schedule:
      interval: "monthly"
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20
