{
  tms {
    tasks {
      nodes {
        projects {
          nodes {
            task {
              projects {
                nodes {
                  task {
                    projects {
                      nodes {
                        task {
                          projects {
                            nodes {
                              task {
                                projects {
                                  nodes {
                                    task {
                                      projects {
                                        nodes {
                                          task {
                                            projects {
                                              nodes {
                                                task {
                                                  projects {
                                                    nodes {
                                                      task {
                                                        projects {
                                                          nodes {
                                                            task {
                                                              projects {
                                                                nodes {
                                                                  task {
                                                                    uid
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
