query paginatedQuery($_offset: Int, $_limit: Int, $from: timestamptz, $to: timestamptz) {
  vcs_Commit(where: {refreshedAt: {_gte: $from, _lt: $to}}, offset: $_offset, limit: $_limit, order_by: {refreshedAt:asc, id: asc}) {
    id
    author {
      ownerId: id
    }
  }
}
