query paginatedQuery($pageSize: Int, $cursor: Cursor, $from: builtin_BigInt) {
  cicd {
    deployments(filter: {refreshedAtMillis: {greaterThanOrEqualTo: $from}}, first: $pageSize, after: $cursor) {
      edges {
        cursor
        node {
          deploymentUid: uid
          application {
            appName: name
          }
          changeset {
            nodes {
              commit {
                sha
              }
            }
          }
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
