query paginatedQuery($_id: String = "", $_limit: Int, $from: timestamptz) {
  cicd_Deployment(
    where: {_and: [{refreshedAt: {_gte: $from}}, {id: {_gt: $_id}}]}
    order_by: {id: asc}
    limit: $_limit
  ) {
    _id: id
    deploymentUid: uid
    application {
      appName: name
    }
    changeset {
      commit {
        sha
      }
    }
  }
}
