{
  vcs_PullRequest(limit: 2, where: {author: {uid: {_is_null: false}}}) {
    number
    repository {
      repositoryName: name
    }
    author {
      authorUid: uid
      identity {
        identity {
          authorIdentityName: fullName
          employee {
            authorLevel: level
          }
        }
      }
    }
  }
}
